main: nexel.wilderness.CommandHandler
name: NexelWilderness
version: 0.2
author: NathanDiepeveen
description: An easy to use /wild plugin with Biome wilding.
api-version: 1.15
commands:
   wild:
      description: The basic wilderness command
