main: nexel.wilderness.CommandHandler
name: NexelWilderness
version: 0.1
author: NathanDiepeveen
description: Simple wilderness command.
api-version: 1.15
commands:
   wild:
      description: The basic wilderness command
